[versions]
agp = "8.5.2"
kotlin = "2.0.20"
bcv = "0.16.3"
mavenPublish = "0.35.0"
androidxAnnotation = "1.8.2"
junit = "4.13.2"
robolectric = "4.13"
androidxTestCore = "1.6.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
