name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - name: Check public API has not changed unintentionally
        run: ./gradlew apiCheck

      - name: Build
        run: ./gradlew assembleRelease

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: background-audit/build/reports/tests/
